friendlier failures

diff --git a/script-templates/lib/publisher/publish b/script-templates/lib/publisher/publish
--- a/script-templates/lib/publisher/publish
+++ b/script-templates/lib/publisher/publish
@@ -54,7 +54,10 @@ echo -e "\nCreating ZIP package $PACKAGE_NAME..."
 zip -r $PACKAGE_PATH * -x .publish.yml -x "utils/*" -x "lib/stub_data/*"
 
 PACKAGE_SIZE=$(wc -c $PACKAGE_PATH | awk '{print $1}')
+[ -z "$PACKAGE_SIZE" ] && echo "Could not determine package size! Aborting." && exit 1
+
 PACKAGE_MD5=($(md5sum $PACKAGE_PATH | awk '{print $1}' | xxd -r -p | base64 -w 0))
+[ -z "$PACKAGE_MD5" ] && echo "Could not determine package checksum! Aborting." && exit 1
 
 echo -e "\nCreating remote script object..."
 
@@ -72,13 +75,17 @@ CREATE_SCRIPT_HTTP_CODE=$(curl $EXTRA_CURL_OPTIONS -L -o /tmp/create_script_resu
   --header "Authorization: Basic $AUTHORIZATION_BASIC" \
   --header "Content-Type: application/json" \
   --header "Accept: application/json" \
-  --data-raw "$CREATE_SCRIPT_PAYLOAD")
+  --data-raw "$CREATE_SCRIPT_PAYLOAD" || true)
 
 echo -e "Completed with result $CREATE_SCRIPT_HTTP_CODE"
 [ "$CREATE_SCRIPT_HTTP_CODE" != "200" ] && echo "Aborting due to an error" && exit 1
 
-UPLOAD_DEST_URL=$(cat /tmp/create_script_result.json | jq -r ".direct_upload.url")
-SCRIPT_ID=$(cat /tmp/create_script_result.json | jq -r ".id")
+UPLOAD_DEST_URL=$(cat /tmp/create_script_result.json | jq -r ".direct_upload.url || true")
+[ -z "$UPLOAD_DEST_URL" ] && echo "Direct upload URL not found! Aborting." && exit 1
+
+SCRIPT_ID=$(cat /tmp/create_script_result.json | jq -r ".id || true")
+[ -z "$SCRIPT_ID" ] && echo "Script ID not found! Aborting." && exit 1
+
 SCRIPT_URL=$SCRIPTS_URL/$SCRIPT_ID
 
 echo -e "\nUploading $PACKAGE_NAME to $UPLOAD_DEST_URL..."
@@ -87,7 +94,7 @@ UPLOAD_HTTP_CODE=$(curl $EXTRA_CURL_OPTIONS -L -o /dev/null -w "%{http_code}" -X
   --header "Content-Length: $PACKAGE_SIZE" \
   --header "Content-Type: application/zip" \
   --header "Content-MD5: $PACKAGE_MD5" \
-  --header "Content-Disposition: inline; filename=\"$PACKAGE_NAME\"; filename*=UTF-8''$PACKAGE_NAME")
+  --header "Content-Disposition: inline; filename=\"$PACKAGE_NAME\"; filename*=UTF-8''$PACKAGE_NAME" || true)
 
 echo -e "Completed with result $UPLOAD_HTTP_CODE"
 [ "$UPLOAD_HTTP_CODE" != "200" ] && echo "Aborting due to an error" && exit 1
@@ -98,7 +105,7 @@ NOTIFY_UPLOADED_CODE=$(curl $EXTRA_CURL_OPTIONS -L -o /dev/null -w "%{http_code}
   --header "Authorization: Basic $AUTHORIZATION_BASIC" \
   --header "Content-Type: application/json" \
   --header "Accept: application/json" \
-  --data-raw "{\"uploaded\": true}")
+  --data-raw "{\"uploaded\": true}" || true)
 
 echo -e "Completed with result $NOTIFY_UPLOADED_CODE"
 [ "$NOTIFY_UPLOADED_CODE" != "202" ] && echo "Aborting due to an error" && exit 1
@@ -110,7 +117,7 @@ until [ $COUNTER -eq 0 ]; do
   NOTIFY_UPLOADED_CODE=$(curl $EXTRA_CURL_OPTIONS -L -s -o /dev/null -w "%{http_code}" -X GET $SCRIPT_URL \
     --header "Authorization: Basic $AUTHORIZATION_BASIC" \
     --header "Content-Type: application/json" \
-    --header "Accept: application/json")
+    --header "Accept: application/json" || true)
   [ "$NOTIFY_UPLOADED_CODE" = "200" ] && break
   COUNTER=$((COUNTER-1))
   echo -n "."
