some reorganization

diff --git a/script-templates/lib/shared/utils/_setup b/script-templates/lib/shared/utils/_setup
--- a/script-templates/lib/shared/utils/_setup
+++ b/script-templates/lib/shared/utils/_setup
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Copyright 2022 Skytap Inc.
 
@@ -14,8 +14,16 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-cd $(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/..
+set -e
 
-source utils/_setup
+DOCKER=$(which podman || which docker)
+[ -n "$DOCKER" ] || (echo "docker or podman is required" && exit 1)
 
-$DOCKER run  --rm -v $PWD:/tmp/course_script -w /tmp/course_script $IMAGE_NAME npm install --no-fund
+IMAGE_NAME_LINE=$(cat config.yml|grep image_name)
+IMAGE_NAME=$(echo ${IMAGE_NAME_LINE#*:}|xargs)
+
+COMMAND_LINE=$(cat config.yml|grep command)
+COMMAND=$(echo ${COMMAND_LINE#*:}|xargs)
+
+ARGS_LINE=$(cat config.yml|grep args)
+ARGS=$(echo ${ARGS_LINE#*:}|xargs)
